In [23]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4,5,6])

print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [25]:
v_add = v1 + v2
v_sup = v1 - v2

print(v_add, v_sup)


[5 7 9] [-3 -3 -3]


In [26]:
scalar = 2
v_scaled = scalar * v1
print(v_scaled)

[2 4 6]


In [27]:
dot_product = np.dot(v1,v2)
print(dot_product)

32


In [28]:
magnitude_v1 = np.linalg.norm(v1)
print(magnitude_v1)

3.7416573867739413


In [33]:
A = np.array([[1,2,3], [4,5,6]])
print(A)
print( )

B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [35]:
C = np.array([[1,2,3],[4,5,6]])
print(C)

[[1 2 3]
 [4 5 6]]


In [43]:
matrix_add = A+C
print("A+C=\n", matrix_add)

matrix_sub = A-C
print("A+C=\n", matrix_sub)


A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A+C=
 [[0 0 0]
 [0 0 0]]


In [45]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [46]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
print("A system oflinear equations takes the form of Ax =b")

A system oflinear equations takes the form of Ax =b


In [50]:
print("A is the coeff matrix, x is vector of unknowns, b is the const vector")

A is the coeff matrix, x is vector of unknowns, b is the const vector


In [55]:
#using matrixes to solve a system of equations
A = np.array([[2,3],[4,-1]])
b = np.array([5,3])
print("matrix A\n", A)
print("matrix b\n", b)
x = np.linalg.solve(A,b)
print("Solution: (x, y):", x)

matrix A
 [[ 2  3]
 [ 4 -1]]
matrix b
 [5 3]
Solution: (x, y): [1. 1.]


In [60]:
#eigenvalues/eigenvectors
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A) #.eig returns two things, so it needs two inputs
print("eigenvalues:\n", eigenvalues, "\neigenvectors \n", eigenvectors)

eigenvalues:
 [3. 1.] 
eigenvectors 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [62]:
#inversed matrix
a = np.array([[2,7],[4,6]])
a_inv = np.linalg,inv(a)
print(a)
print(a_inv)

NameError: name 'inv' is not defined